sudo: required
dist: trusty
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools


    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-22


    #: Add android image
    - android-22 # Android platform used by your alternative emulator
    - sys-img-armeabi-v7a-android-22
    - extra-google-m2repository
    - extra-android-m2repository



branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=2.7

before_install:
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
     else
       wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Create env
  - conda install python -q

  # Install the cli
  - pip install --user enaml-native git+https://github.com/codelv/enaml-native-cli.git

  # Start the emulator
  - android list target
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

  # Install enamlnative dependencies
  - pip install --user enaml==0.9.8 ply msgpack-python

  # Install test tools
  - pip install --user pytest pytest-cov pytest-timeout

  # Install codecov report tools
  - pip install --user codecov

install:

  # Install enamlnative (check that build script is not broken
  - cd $TRAVIS_BUILD_DIR
  - python setup.py develop --user
  - cd ~

script:
  # Run the enaml test suite
  - cd $TRAVIS_BUILD_DIR
  - py.test tests --cov enamlnative --cov-report xml -v

after_success:
  - cd $TRAVIS_BUILD_DIR
  - codecov
