sudo: false
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=2.7

before_install:

  # Install enamlnative dependencies
  - pip install enaml ply msgpack-python

  # Intall test tools
  - pip install pytest pytest-cov pytest-catchlog pytest-timeout

  # Install codecov report tools
  - pip install codecov

install:

  # Install ecpy (check that build script is not broken
  - cd $TRAVIS_BUILD_DIR
  - python setup.py develop
  - cd ~

script:
  # Run the enaml test suite
  - cd $TRAVIS_BUILD_DIR
  - py.test tests --cov enamlnative --cov-report xml -v

after_success:
  - cd $TRAVIS_BUILD_DIR
  - codecov
