sudo: required
dist: precise
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools


    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26

branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=2.7

before_install:
  #: Setup Python
  - sudo dpkg --add-architecture i386
  - sudo apt update
  - sudo apt install -y build-essential ccache git zlib1g-dev python2.7 python2.7-dev python-virtualenv libncurses5:i386 libstdc++6:i386 zlib1g:i386 unzip ant ccache autoconf libtool
  - sudo apt install -y openjdk-8-jdk

  # Start the emulator!
  - android list target
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

  #: Install cython
  - pip install Cython --install-option="--no-cython-compile"

  # Install enamlnative dependencies
  - pip install enaml==0.9.8 ply msgpack-python

  # Install p4a dependencies
  - pip install sh colorama appdirs six jinja2

  # Install test tools
  - pip install pytest pytest-cov pytest-timeout

  # Install the cli
  - pip install enaml-native-cli

  # Install codecov report tools
  - pip install codecov

install:

  # Install enamlnative (check that build script is not broken
  - cd $TRAVIS_BUILD_DIR
  - python src/setup.py develop
  - cd ~

script:
  # Run the enaml test suite
  - cd $TRAVIS_BUILD_DIR
  - py.test tests --cov enamlnative --cov-report xml -v

after_success:
  - cd $TRAVIS_BUILD_DIR
  - codecov
