package:
  name: enaml-native
  version: 4.5.0

requirements:
  build:
    - python

  run:
    - android-enaml
    - android-msgpack
    - ios-enaml # [osx]
    - ios-msgpack # [osx]

build:
  number: 5
  noarch: generic
  include_recipe: False

about:
  home: http://github.com/codelv/enaml-native
  license: MIT