name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: pip install -U wheel tornado msgpack codecov pytest pytest-cov pytest-asyncio
      - name: Install latest dependencies
        run: |
            pip install --user git+https://github.com/nucleic/atom.git
            pip install --user git+https://github.com/frmdstryr/enaml.git@d-change-types
      - name: Install cli
        run: |
            pip install --user git+https://github.com/codelv/enaml-native-cli.git
            enaml-native -h
      - name: Install enaml-native
        run: pip install -e ./
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Install android system image and emulator
        run: |
          sdkmanager --list
          sdkmanager --install "system-images;android-30;google_apis;x86_64"
          sdkmanager --install "emulator"
      - name: Create avd
        run: |
          echo no | avdmanager create avd --force --name test -k "system-images;android-30;google_apis;x86_64"
          avdmanager list avd
      - name: Start emulator
        run: |
          export PATH="$PATH:$ANDROID_HOME/emulator"
          emulator -avd test -no-audio -no-window -no-accel &
          timeout 300 adb wait-for-device
          adb devices
      - name: Run tests
        run: pytest -v tests --cov enamlnative --cov-report xml --asyncio-mode auto
      - name: Coverage
        run: codecov
  check-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -U mypy black isort flake8
      - name: Run checks
        run: |
            isort src --check --diff
            isort tests --check --diff
            isort docs --check --diff
            black src --check --diff
            black tests --check --diff
            black docs --check --diff
            flake8 --ignore=E501,W503 src
            flake8 --ignore=E501,W503 tests
            flake8 --ignore=E501,W503 docs
            mypy src/enamlnative --ignore-missing-imports


